import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { getMatches, sendExchangeRequest, getMySkills } from '../../../lib/apiClient';
import { MatchCandidate, UserSkill } from '../../../types';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { Badge } from '../../../components/ui/Badge';
import {
  Sparkles, Users2, TrendingUp, Star, Clock, Zap,
  BookOpen, ChevronRight, RefreshCw, ArrowLeftRight,
} from 'lucide-react';

const ScoreBar: React.FC<{ label: string; value: number; color: string }> = ({ label, value, color }) => (
  <div className="space-y-1">
    <div className="flex justify-between text-[11px] text-slateText-500">
      <span>{label}</span>
      <span className="font-medium">{Math.round(value * 100)}%</span>
    </div>
    <div className="h-1.5 bg-surface-200 rounded-full overflow-hidden">
      <div
        className={`h-full rounded-full ${color} transition-all duration-700`}
        style={{ width: `${Math.round(value * 100)}%` }}
      />
    </div>
  </div>
);

const scoreColor = (v: number) =>
  v >= 0.8 ? 'bg-teal-500' : v >= 0.6 ? 'bg-aiBlue' : v >= 0.4 ? 'bg-amber-400' : 'bg-surface-300';

export const MatchesPage: React.FC = () => {
  const navigate = useNavigate();
  const [matches, setMatches] = useState<MatchCandidate[]>([]);
  const [mySkills, setMySkills] = useState<UserSkill[]>([]);
  const [loading, setLoading] = useState(true);
  const [requesting, setRequesting] = useState<string | null>(null);
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const load = async () => {
    setLoading(true);
    try {
      const [m, s] = await Promise.all([getMatches(), getMySkills()]);
      setMatches(Array.isArray(m) ? m : []);
      setMySkills(Array.isArray(s) ? s : []);
    } catch { /* silent */ }
    finally { setLoading(false); }
  };

  useEffect(() => { load(); }, []);

  const handleRequest = async (candidateId: string, wantedSkillId: string) => {
    const offered = mySkills.find((s) => s.canTeach);
    if (!offered) return;
    setRequesting(candidateId);
    try {
      await sendExchangeRequest({
        receiverId: candidateId,
        offeredSkillId: offered.skillId,
        wantedSkillId,
      });
      alert('Exchange request sent!');
    } catch (e: unknown) {
      const err = e as { response?: { data?: { message?: string } } };
      alert(err?.response?.data?.message ?? 'Request failed');
    } finally { setRequesting(null); }
  };

  const totalScore = (m: MatchCandidate) =>
    (m.scores.skillCompatibility +
      m.scores.goalAlignment +
      m.scores.availabilityOverlap +
      m.scores.proficiencyBalance +
      m.scores.trustScore) / 5;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slateText-900 tracking-tight flex items-center gap-2">
            <Users2 className="w-6 h-6 text-teal-500" />
            AI Matches
          </h1>
          <p className="text-sm text-slateText-500 mt-0.5">
            Peer compatibility scored across 5 dimensions
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={load}>
          <RefreshCw className={`w-3.5 h-3.5 mr-1.5 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </Button>
      </div>

      {/* AI badge strip */}
      <div className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-teal-50 to-blue-50 border border-teal-200/60 rounded-panel">
        <Sparkles className="w-4 h-4 text-teal-500 shrink-0" />
        <p className="text-xs text-slateText-600">
          Matches are generated by the <span className="font-semibold text-teal-700">SkillBarter AI Engine</span> using skill compatibility, learning goals, availability overlap, proficiency balance, and trust score.
        </p>
        <Badge variant="ai" className="ml-auto shrink-0">Live</Badge>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-72 bg-surface-100 rounded-panel animate-pulse" />
          ))}
        </div>
      ) : matches.length === 0 ? (
        <Card className="p-12 text-center">
          <TrendingUp className="w-10 h-10 text-surface-300 mx-auto mb-3" />
          <p className="text-sm font-medium text-slateText-600">No matches found yet</p>
          <p className="text-xs text-slateText-400 mt-1">Add teachable skills and learning goals to generate matches</p>
          <Button variant="outline" size="sm" className="mt-4" onClick={() => navigate('/skills')}>
            Add Skills
          </Button>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-5">
          {matches.map((m) => {
            const score = totalScore(m);
            const expanded = expandedId === m.candidateUserId;
            return (
              <Card
                key={m.candidateUserId}
                className="p-5 hover:shadow-md transition-all duration-200 flex flex-col gap-4"
              >
                {/* Avatar + name */}
                <div className="flex items-start gap-3">
                  <div className="w-11 h-11 rounded-full bg-gradient-to-br from-teal-400 to-aiBlue text-white font-bold flex items-center justify-center text-sm shrink-0 shadow">
                    {m.firstName[0]}{m.lastName[0]}
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-semibold text-slateText-900 text-sm">
                      {m.firstName} {m.lastName}
                    </h3>
                    <p className="text-xs text-slateText-400 truncate">{m.email}</p>
                  </div>
                  {/* Overall score pill */}
                  <div className={`shrink-0 text-xs font-bold px-2.5 py-1 rounded-full text-white shadow-sm ${
                    score >= 0.8 ? 'bg-teal-500' : score >= 0.6 ? 'bg-aiBlue' : 'bg-amber-400'
                  }`}>
                    {Math.round(score * 100)}%
                  </div>
                </div>

                {/* Skill tags */}
                <div className="space-y-1.5">
                  {m.canTeachSkills.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      <span className="text-[10px] text-slateText-400 mr-1 self-center">Teaches:</span>
                      {m.canTeachSkills.slice(0, 3).map((s) => (
                        <span key={s.skillId} className="text-[10px] bg-teal-50 text-teal-700 border border-teal-200 px-1.5 py-0.5 rounded font-medium">
                          {s.skillName}
                        </span>
                      ))}
                    </div>
                  )}
                  {m.wantToLearnSkills.length > 0 && (
                    <div className="flex flex-wrap gap-1">
                      <span className="text-[10px] text-slateText-400 mr-1 self-center">Wants:</span>
                      {m.wantToLearnSkills.slice(0, 3).map((s) => (
                        <span key={s.skillId} className="text-[10px] bg-blue-50 text-aiBlue border border-blue-200 px-1.5 py-0.5 rounded font-medium">
                          {s.skillName}
                        </span>
                      ))}
                    </div>
                  )}
                </div>

                {/* Score breakdown toggle */}
                <button
                  onClick={() => setExpandedId(expanded ? null : m.candidateUserId)}
                  className="flex items-center justify-between text-[11px] text-slateText-500 hover:text-slateText-700 transition-colors"
                >
                  <span className="font-medium">Score Breakdown</span>
                  <ChevronRight className={`w-3.5 h-3.5 transition-transform ${expanded ? 'rotate-90' : ''}`} />
                </button>

                {expanded && (
                  <div className="space-y-2 pt-1 border-t border-surface-100">
                    <ScoreBar label="Skill Compatibility"  value={m.scores.skillCompatibility}  color={scoreColor(m.scores.skillCompatibility)} />
                    <ScoreBar label="Goal Alignment"       value={m.scores.goalAlignment}        color={scoreColor(m.scores.goalAlignment)} />
                    <ScoreBar label="Availability Overlap" value={m.scores.availabilityOverlap}  color={scoreColor(m.scores.availabilityOverlap)} />
                    <ScoreBar label="Proficiency Balance"  value={m.scores.proficiencyBalance}   color={scoreColor(m.scores.proficiencyBalance)} />
                    <ScoreBar label="Trust Score"          value={m.scores.trustScore}           color={scoreColor(m.scores.trustScore)} />
                  </div>
                )}

                {/* Stats row */}
                <div className="flex items-center gap-3 text-[11px] text-slateText-500 pt-1 border-t border-surface-100">
                  <span className="flex items-center gap-1"><Star className="w-3 h-3 text-amber-400" />{m.trustScore.toFixed(1)}</span>
                  <span className="flex items-center gap-1"><Clock className="w-3 h-3 text-teal-400" />{m.availabilitySlotsCount} slots</span>
                  <span className="flex items-center gap-1"><BookOpen className="w-3 h-3 text-aiBlue" />{m.totalSessionsCompleted} done</span>
                  <span className="flex items-center gap-1"><Zap className="w-3 h-3 text-violet-400" />{m.creditBalance} cr</span>
                </div>

                {/* Actions */}
                <div className="flex gap-2 mt-auto">
                  <Button
                    size="sm"
                    variant="outline"
                    className="flex-1"
                    onClick={() => navigate(`/users/${m.candidateUserId}`)}
                  >
                    Profile
                  </Button>
                  <Button
                    size="sm"
                    className="flex-1"
                    onClick={() => {
                      const skill = m.canTeachSkills[0];
                      if (skill) handleRequest(m.candidateUserId, skill.skillId);
                    }}
                    disabled={requesting === m.candidateUserId || m.canTeachSkills.length === 0}
                  >
                    <ArrowLeftRight className="w-3.5 h-3.5 mr-1.5" />
                    {requesting === m.candidateUserId ? 'Sending…' : 'Request'}
                  </Button>
                </div>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
};
